# -*- coding: utf-8 -*-
"""AI-powered resume tailoring web application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g79Sda43xGERTDC68QqDyW_AdVzOc_BE
"""
# ======================================================================
# Install Required Libraries
# ======================================================================
!pip install openai python-docx PyPDF2 gradio -q

# ======================================================================
# Import Libraries and Setup
# ======================================================================
print("✅ All libraries installed successfully!")

from openai import OpenAI
import gradio as gr
from google.colab import files
import PyPDF2
import docx
import json
import io
from typing import Tuple, Dict

print("✅ Libraries imported successfully!")
# ======================================================================
# Configure OpenAI API Key
# ======================================================================

"""
Get your OpenAI API key from:
https://platform.openai.com/account/api-keys
"""

# Option 1: Paste API Key directly
API_KEY = ""# 🔑 Paste your OpenAI API key here

# Option 2: Upload API key from file
def load_api_key_from_file():
    uploaded = files.upload()
    for filename in uploaded.keys():
        with open(filename, 'r') as f:
            return f.read().strip()
    return None

# Uncomment to upload key instead
# API_KEY = load_api_key_from_file()

if not API_KEY:
    print("⚠️ Please set your OPENAI API key")
else:
    print("✅ API Key configured!")
    client = OpenAI(api_key=API_KEY)

# ============================================================================
# Document Processing Functions
# ============================================================================

def extract_text_from_pdf(file_path: str) -> str:
    """Extract text from PDF file"""
    try:
        with open(file_path, 'rb') as file:
            pdf_reader = PyPDF2.PdfReader(file)
            text = ""
            for page in pdf_reader.pages:
                text += page.extract_text() + "\n"
            return text.strip()
    except Exception as e:
        return f"Error reading PDF: {str(e)}"


def extract_text_from_docx(file_path: str) -> str:
    """Extract text from DOCX file"""
    try:
        doc = docx.Document(file_path)
        text = ""
        for paragraph in doc.paragraphs:
            text += paragraph.text + "\n"
        return text.strip()
    except Exception as e:
        return f"Error reading DOCX: {str(e)}"


def extract_text_from_doc(file_path: str) -> str:
    """Extract text from DOC file (legacy format)"""
    return "Note: .doc files require conversion. Please save as .docx or .pdf and upload again."


def process_resume_file(file_path: str) -> str:
    """Process uploaded resume file and extract text"""
    if not file_path:
        return "No file uploaded"

    file_extension = file_path.lower().split('.')[-1]

    if file_extension == 'pdf':
        return extract_text_from_pdf(file_path)
    elif file_extension == 'docx':
        return extract_text_from_docx(file_path)
    elif file_extension == 'doc':
        return extract_text_from_doc(file_path)
    else:
        return "Unsupported file format. Please upload PDF, DOC, or DOCX."


print("✅ Document processing functions loaded!")

# ======================================================================
# AI Resume Tailoring (OpenAI)
# ======================================================================

def tailor_resume_with_ai(resume_text: str, job_description: str) -> Tuple[str, Dict]:
    """
    Use OpenAI GPT to analyze and tailor the resume
    """

    if not resume_text or not job_description:
        return "Error: Please provide both resume and job description", {}

    if not API_KEY:
        return "Error: API key not configured", {}

    try:
        prompt = f"""
You are an expert resume writer and career coach.

ORIGINAL RESUME:
{resume_text}

JOB DESCRIPTION:
{job_description}

Return ONLY valid JSON in the following structure:

{{
  "analysis": {{
    "matchPercentage": 75,
    "keyStrengths": ["strength1", "strength2"],
    "gaps": ["gap1", "gap2"],
    "recommendations": ["rec1", "rec2"]
  }},
  "tailoredResume": "Full tailored resume text"
}}

Rules:
- Do NOT add fake experience
- Optimize for ATS
- Use job keywords naturally
- No markdown
- No explanations
"""

        response = client.responses.create(
            model="gpt-4.1-mini",  # or "gpt-4o" / "gpt-4.1"
            input=[
                {
                    "role": "user",
                    "content": prompt
                }
            ],
            max_output_tokens=4000,
        )

        response_text = response.output_text.strip()

        # Safety cleanup
        response_text = response_text.replace("```json", "").replace("```", "").strip()

        result = json.loads(response_text)

        return result["tailoredResume"], result["analysis"]

    except Exception as e:
        return f"Error: {str(e)}", {}
# ======================================================================
# Gradio UI Logic
# ======================================================================

def create_analysis_html(analysis: Dict) -> str:
    if not analysis:
        return ""

    return f"""
    <div style="padding:20px;border-radius:10px;background:#111827;color:white">
        <h2>📊 Resume Match: {analysis.get('matchPercentage',0)}%</h2>

        <h3>✅ Strengths</h3>
        <ul>{"".join(f"<li>{s}</li>" for s in analysis.get("keyStrengths",[]))}</ul>

        <h3>⚠️ Gaps</h3>
        <ul>{"".join(f"<li>{g}</li>" for g in analysis.get("gaps",[]))}</ul>

        <h3>💡 Recommendations</h3>
        <ul>{"".join(f"<li>{r}</li>" for r in analysis.get("recommendations",[]))}</ul>
    </div>
    """


def process_and_tailor(resume_file, job_desc):
    if not resume_file:
        return "Upload resume", "", ""

    resume_text = process_resume_file(resume_file.name)

    if resume_text.startswith("Error") or resume_text.startswith("Note"):
        return resume_text, "", ""

    tailored, analysis = tailor_resume_with_ai(resume_text, job_desc)
    return resume_text, create_analysis_html(analysis), tailored

# ======================================================================
# Gradio Interface
# ======================================================================
with gr.Blocks(theme=gr.themes.Soft(), title="AI Resume Tailor") as demo:

    gr.Markdown("# 🎯 AI Resume Tailor (OpenAI Powered)")

    with gr.Row():
        resume_file = gr.File(label="Upload Resume", file_types=[".pdf",".docx"])
        job_desc = gr.Textbox(label="Job Description", lines=15)

    original = gr.Textbox(label="Extracted Resume", lines=10)
    analysis = gr.HTML()
    tailored = gr.Textbox(label="Tailored Resume", lines=20)

    btn = gr.Button("✨ Tailor Resume")

    btn.click(
        fn=process_and_tailor,
        inputs=[resume_file, job_desc],
        outputs=[original, analysis, tailored]
    )
# ======================================================================
# Launch App
# ======================================================================
if not API_KEY:
    print("❌ API Key missing")
else:
    print("🚀 Launching app...")
    demo.launch(share=True, debug=True)
